trapper/trapper-project/trapper/apps/geomap/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.views.decorators.cache import never_cache

from leaflet_storage.utils import decorated_patterns
from leaflet_storage.decorators import map_permissions_check
from leaflet_storage import views as ls_views

from rest_framework.routers import DefaultRouter

from trapper.apps.geomap.views import api as api_views
from trapper.apps.geomap.views import map as map_views
from trapper.apps.geomap.views import location as location_views
from trapper.apps.geomap.views import deployment as deployment_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'locations',
    api_views.LocationViewSet,
    base_name='api-location'
)

router.register(
    r'deployments',
    api_views.DeploymentViewSet,
    base_name='api-deployment'
)

router.register(
    r'maps',
    api_views.MapViewSet,
    base_name='api-map'
)

urlpatterns = [
    url(
        r'^api/locations/export/$',
        api_views.LocationTableView.as_view(),
        name='api-location-export'
    ),
    url(
        r'^api/deployments/export/$',
        api_views.DeploymentTableView.as_view(),
        name='api-deployment-export'
    ),
    url(
        r'^api/locations/geojson/$',
        api_views.LocationGeoViewSet.as_view(),
        name='api-location-geojson'
    ),
    url(r'^api/', include(router.urls))
]

urlpatterns += [

    url(
        r'^location/bulk-update/$',
        location_views.view_location_bulk_update,
        name='location_bulk_update'
    ),
    url(
        r'^location/create/$',
        RedirectView.as_view(url=u'/geomap/map/?action=create'),
        name='location_create'
        ),
    url(
        r'^location/(?P<pk>\d+)/delete/$',
        location_views.view_location_delete,
        name='location_delete'
    ),
    url(
        r'^location/delete/$',
        location_views.view_location_delete,
        name='location_delete_multiple'
    ),
    url(r'^location/list/$',
        location_views.view_location_list,
        name='location_list'
    ),
    url(
        r'^location/import/$',
        location_views.view_location_import,
        name='location_import'
    ),
    url(
        r'^location/filterform/$',
        location_views.view_location_filter_form,
        name="locations_filterform"
    ),
    url(
        r'^location/createform/$',
        location_views.view_location_create_form,
        name="locations_createform"
    ),
    url(
        r'^location/(?P<pk>\d+)/editform/$',
        location_views.view_location_edit_filter_form,
        name="locations_editform"
    ),
    url(
        r'^location/collections/$',
        location_views.view_location_collections,
        name="location_collections"
    ),
]

urlpatterns += [

    url(
        r'^map/permissions/update/(?P<map_id>[\d]+)/$',
        map_views.view_update_map_permissions,
        name="map_permissions"
    ),
    url(
        r'^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$',
        map_views.view_map, 
        name='map'
    ),
    url(
        r'^map/list/$', 
        map_views.view_map_list, 
        name="map_list"),
    url(
        r'^map/(?P<pk>\d+)/delete/$',
        map_views.view_map_delete,
        name='map_delete'
    ),
    url(
        r'^map/delete/$',
        map_views.view_map_delete,
        name='map_delete_multiple'
    ),
    url(
        r'^map/$', 
        map_views.view_new_map, 
        name='map_view'
    ),
    url(
        r'permissions/update/(?P<map_id>\d+)/$',
        map_views.view_update_map_permissions,
        name='map_permissions'
    ),
    url(
        r'^map/create/$', 
        map_views.view_map_create, 
        name='map_create'
    ),
]

urlpatterns += [
    url(r'^map/(?P<map_id>[\d]+)/update/settings/$',
        ls_views.MapUpdate.as_view(), name='map_update'),
    url(r'^map/(?P<map_id>[\d]+)/update/permissions/$',
        ls_views.UpdateMapPermissions.as_view(),
        name='map_update_permissions'),
    url(r'^map/(?P<map_id>[\d]+)/update/delete/$',
        ls_views.MapDelete.as_view(), name='map_delete'),
    url(r'^map/(?P<map_id>[\d]+)/update/clone/$',
        ls_views.MapClone.as_view(), name='map_clone'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/create/$',
        ls_views.DataLayerCreate.as_view(), name='datalayer_create'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$',
        ls_views.DataLayerUpdate.as_view(), name='datalayer_update'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$',
        ls_views.DataLayerDelete.as_view(), name='datalayer_delete'),
]

urlpatterns += [

    # Deployments
    url(
        r'^deployment/$',
        RedirectView.as_view(url=reverse_lazy('geomap:deployment_list')),
        name='deployment_index'
    ),
    url(
        r'^deployment/list/$',
        deployment_views.view_deployment_list,
        name='deployment_list'
    ),
    url(
        r'^deployment/detail/(?P<pk>\d+)/$',
        deployment_views.view_deployment_detail,
        name='deployment_detail'
    ),
    url(
        r'^deployment/delete/(?P<pk>\d+)/$',
        deployment_views.view_deployment_delete,
        name='deployment_delete'
    ),
    url(
        r'^deployment/delete/$',
        deployment_views.view_deployment_delete,
        name='deployment_delete_multiple'
    ),
    url(
        r'^deployment/create/$',
        deployment_views.view_deployment_create,
        name='deployment_create'
    ),
    url(
        r'^deployment/update/(?P<pk>\d+)/$',
        deployment_views.view_deployment_update,
        name='deployment_update'
    ),
    url(
        r'^deployment/bulk-update/$',
        deployment_views.view_deployment_bulk_update,
        name='deployment_bulk_update'
    ),
    url(
        r'^deployment/bulk-create/$',
        deployment_views.view_deployment_bulk_create,
        name='deployment_bulk_create'
    ),
    url(
        r'deployment/import/$',
        deployment_views.view_deployment_import,
        name='deployment_import'
    ),
]

trapper/trapper-project/trapper/apps/media_classification/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from trapper.apps.media_classification.views import (
    api as classification_api_views
)
from trapper.apps.media_classification.views import (
    classifications as classifications_views,
    user_classifications as user_classifications_views,
    projects as projects_views,
    classificators as classificators_views,
    sequences as sequences_views 
)


router = DefaultRouter(trailing_slash=False)

router.register(
    r'classificators',
    classification_api_views.ClassificatorViewSet,
    base_name='api-classificator'
)

router.register(
    r'user-classifications',
    classification_api_views.UserClassificationViewSet,
    base_name='api-user-classification'
)

router.register(
    r'classifications',
    classification_api_views.ClassificationViewSet,
    base_name='api-classification'
)

router.register(
    r'classifications_map',
    classification_api_views.ClassificationMapViewSet,
    base_name='api-classification-map'
)

router.register(
    r'classification-projects',
    classification_api_views.ClassificationProjectViewSet,
    base_name='api-classification-project'
)

router.register(
    r'classification-project-collections',
    classification_api_views.ClassificationProjectCollectionViewSet,
    base_name='api-classification-project-collection'
)

router.register(
    r'sequences',
    classification_api_views.SequenceViewSet,
    base_name='api-sequence'
)

router.register(
    r'classification/(?P<collection_pk>\d+)/(?P<current_resource_pk>\d+)/resources/$',
    classification_api_views.ClassificationResourcesViewSet,
    base_name='api-classification-resources'
)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(
        r'^api/classifications/results/(?P<project_pk>\d+)/',
        classification_api_views.ClassificationResultsView.as_view(),
        name='api-classification-results'
    ),
    url(
        r'^api/classifications/results/agg/(?P<project_pk>\d+)/',
        classification_api_views.ClassificationResultsAggView.as_view(),
        name='api-classification-results-agg'
    ),
    url(
        r'^api/classifications/import',
        classification_api_views.ClassificationImport.as_view(),
        name='api-classification-import'
    )
]

urlpatterns += [

    url(
        r'^$',
        RedirectView.as_view(
            url=reverse_lazy('media_classification:project_list')
        ),
        name='project_index'
    ),

    # Project views
    url(
        r'project/list/$',
        projects_views.view_project_list, 
        name='project_list'
    ),
    url(
        r'project/detail/(?P<pk>\d+)/$',
        projects_views.view_project_detail,
        name='project_detail'
    ),

    url(
        r'project/create/$', 
        projects_views.view_project_create,
        name='project_create'
    ),
    url(
        r'project/update/(?P<pk>\d+)/$', 
        projects_views.view_project_update,
        name='project_update'
    ),
    url(
        r'project/delete/(?P<pk>\d+)/$',
        projects_views.view_project_delete,
        name='project_delete'
    ),
    url(
        r'^project/delete/$',
        projects_views.view_project_delete,
        name='project_delete_multiple'
    ),
    url(
        r'project/collection/add/$',
        projects_views.view_project_collection_add,
        name='project_collection_add'
    ),
    url(
        r'project/collection/delete/(?P<pk>\d+)/$',
        projects_views.view_project_collection_delete,
        name='project_collection_delete'
    ),
    url(
        r'^project/collection/delete/$',
        projects_views.view_project_collection_delete,
        name='project_collection_delete_multiple'
    ),

    # Classificator views
    url(
        r'classificator/list/$', 
        classificators_views.view_classificator_list,
        name='classificator_list'
    ),
    url(
        r'classificator/detail/(?P<pk>\d+)/$',
        classificators_views.view_classificator_detail, 
        name='classificator_detail'
    ),

    url(
        r'classificator/create/$', 
        classificators_views.view_classificator_create,
        name='classificator_create'
    ),
    url(
        r'classificator/update/(?P<pk>\d+)/$',
        classificators_views.view_classificator_update,
        name='classificator_update'
    ),
    url(
        r'classificator/clone/(?P<pk>\d+)/$',
        classificators_views.view_classificator_clone,
        name='classificator_clone'
    ),
    url(
        r'^classificator/delete/(?P<pk>\d+)/$',
        classificators_views.view_classificator_delete,
        name='classificator_delete'
    ),
    url(
        r'^classificator/delete/$',
        classificators_views.view_classificator_delete,
        name='classificator_delete_multiple'
    ),

    # Sequence views
    url(
        r'sequence/create/$',
        sequences_views.view_sequence_change,
        name='sequence_create'
    ),
    url(
        r'sequence/update/$',
        sequences_views.view_sequence_change,
        name='sequence_update'
    ),
    url(
        r'sequence/change/$',
        sequences_views.view_sequence_change,
        name='sequence_change'
    ),
    url(
        r'sequence/delete/$',
        sequences_views.view_sequence_delete,
        name='sequence_delete'
    ),
    url(
        r'^sequence/build/$',
        sequences_views.view_sequence_build,
        name='sequence_build'
    ),

    # Classification views
    url(
        r'classification/detail/(?P<pk>\d+)/$',
        classifications_views.view_classification_detail,
        name='classification_detail'
    ),
    url(
        r'^classification/list/(?P<pk>\d+)/$',
        classifications_views.view_classification_list,
        name='classification_list'
    ),
    url(
        r'classification/import/$',
        classifications_views.view_classification_import,
        name='classification_import'
    ),
    url(
        r'classification/import/(?P<pk>\d+)/$',
        classifications_views.view_classification_import,
        name='classification_import'
    ),
    url(
        r'classification/export/(?P<pk>\d+)/$',
        classifications_views.view_classification_export,
        name='classification_export'
    ),
    url(
        r'classification/form/(?P<pk>\d+)/$',
        classifications_views.view_classification_tag,
        name='classification_tag'
    ),
    url(
        r'classification/delete/(?P<pk>\d+)/$',
        classifications_views.view_classification_delete,
        name='classification_delete'
    ),
    url(
        r'classification/delete/$',
        classifications_views.view_classification_delete,
        name='classification_delete_multiple'
    ),
    url(
        r'classify/(?P<project_pk>\d+)/(?P<collection_pk>\d+)/$',
        classifications_views.view_classify_collection,
        name='classify_collection'
    ),
    url(
        r'classify/(?P<pk>\d+)/$',
        classifications_views.view_classify_resource,
        name='classify'
    ),
    url(
        r'classify/(?P<pk>\d+)/user/(?P<user_pk>\d+)/$',
        classifications_views.view_classify_resource,
        name='classify_user'
    ),
    url(
        r'classify/approve/(?P<pk>\d+)/$',
        classifications_views.view_classify_approve,
        name='classify_approve'
    ),

    # UserClassification views
    url(
        r'user_classification/list/(?P<pk>\d+)/$',
        user_classifications_views.view_user_classification_list,
        name='user_classification_list'
    ),
    url(
        r'user_classification/approve/(?P<pk>\d+)/$',
        user_classifications_views.view_user_classification_bulk_approve,
        name='user_classification_bulk_approve'
    )

]

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from trapper.apps.accounts.views import accounts as accounts_views

admin.autodiscover()

urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    url(
        r'^account/inactive/$',
        RedirectView.as_view(url=reverse_lazy('trapper_index')),
        name='account_inactive'
    ),
    # Trapper homepage
    url(
        r'^$',
        accounts_views.view_index,
        name='trapper_index'
    ),
    # Media classification urls
    url(
        r'^media_classification/',
        include(
            'trapper.apps.media_classification.urls',
            namespace='media_classification'
        )
    ),
    # Research urls
    url(
        r'^research/',
        include(
            'trapper.apps.research.urls',
            namespace='research'
        )
    ),
    # Storage urls
    url(
        r'^storage/',
        include(
            'trapper.apps.storage.urls',
            namespace='storage'
        )
    ),
    # Messaging urls
    url(
        r'^messaging/',
        include(
            'trapper.apps.messaging.urls',
            namespace='messaging'
        )
    ),
    # Accounts urls
    url(
        '',
        include('django.contrib.auth.urls')
    ),
    url(
        r'^accounts/',
        include(
            'trapper.apps.accounts.urls',
            namespace='accounts'
        )
    ),
    url(
        r'^account/',
        include('allauth.urls')
    ),
    # GeoMap urls
    url(
        r'^geomap/',
        include(
            'trapper.apps.geomap.urls',
            namespace='geomap'
        )
    ),
    # Comments
    url(
        r'^comments/',
        include(
            'trapper.apps.comments.urls',
            namespace='comments'
        )
    ),
    # Sendfile urls
    url(
        r'^serve/',
        include(
            'trapper.apps.sendfile.urls',
            namespace='sendfile'
        )
    ),
    # Forum
    url(
        r'^forum/',
        include(
            'djangobb_forum.urls',
            namespace='djangobb'
        )
    ),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_gis/', include(admin_gis.site.urls)),
    url(r'', include('leaflet_storage.urls')),
    # REST API Swagger docs
    url(r'^docs/api/', include('rest_framework_swagger.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = urlpatterns + [
        url(
            r'^__debug__/', 
            include(debug_toolbar.urls)
        )
    ] + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/classification_box.html
{% if user_classifications %}
<table class="table classification-box">
  <tbody>
    {% if classification.status %}
    <tr>
      <td colspan="3"><h4>This resource has classification <strong>approved</strong> by</h4></td>
    </tr>
    <tr class="success">
      <td>
	<span class="fa fa-user"></span>
	<a href="{% url 'accounts:show_profile' classification.approved_by.username %}">
	  {{ classification.approved_by|pretty_username }}
	</a> at 
	{{ classification.approved_at|date:"d.m.Y H:i:s" }}
	<br> The source (user) classification is marked in green below.
      </td>
      <td>
	{% if classification.approved_at < classification.approved_source.updated_at %}
	<action-warning ng-click="execute($event, 'The source classification (by <strong>{{ classification.approved_source.owner|pretty_username }}</strong>) was changed. Consider approving it one more time.')"></action-warning>
	{% endif %}					   
      </td>
    </tr>
    {% else %}
    <tr>
      <td colspan="3"><h4>This resource has no approved classification yet</h4></td>
    </tr>
    {% endif %}
  </tbody>
</table>

<table class="table classification-box">
  <thead>
    <tr>
      <td colspan="3"><h4>User classifications</h4></td>
    </tr>
  <tr>
    <th>User</th>
    <th>Date updated</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  {% for classification_item in user_classifications %}
    <tr {% if classification.approved_source.pk == classification_item.pk %} class="success" {% endif %}{% if classification_item.pk == user_classification.pk %} style="border: 3px solid; border-color: green; border-right: 0 none; border-left: 0 none;"{% endif %}>
      <td>
        <span class="fa fa-user"></span>
	<a href="{% url 'accounts:show_profile' classification_item.owner.username %}">{{ classification_item.owner|pretty_username }}</a>
      </td>
      <td>{{ classification_item.updated_at|date:"d.m.Y H:i:s" }}</td>
      <td>
        {% if classification_item.can_view %}
        <a href="{% url 'media_classification:classification_detail' pk=classification_item.pk %}" class="btn btn-xs btn-default" title="Display"><span class="fa fa-search"></span></a>
        {% endif %}

        {% if classification_item.can_update %}
        <a href="{% url 'media_classification:classify_user' pk=classification.pk user_pk=classification_item.owner.pk %}" class="btn btn-xs btn-default" title="Update"><span class="fa fa-pencil"></span></a>
        {% endif %}

        {% if classification.can_approve %}
        <a href="{% url 'media_classification:classify_approve' pk=classification_item.pk %}" class="btn btn-xs btn-primary btn-approve" title="Approve"><span class="fa fa-check"></span></a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
</tbody>
</table>

{% if classification.status and not request_user_classification %}
<h4 style="padding-left: 15px">You can still add 
  <a href="{% url 'media_classification:classify' pk=classification.pk %}?add_my_classification=True">
    your own classification.
  </a>
</h4>
{% endif %}


{% else %}
  <div class="alert alert-warning ng-binding"><span class="fa fa-info"></span> This resource has not been classified yet.</div>
{% endif %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/comment_box.html
{% load user_comments %}
<div class="tab-pane" id="tab-1">
  {% get_comments item=project show_header=False %}
</div>

<div class="tab-pane" id="tab-2">
  {% if not is_readonly %}
  {% get_comment_form item=project show_header=False %}
  {% endif %}
</div>

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/form_button_box.html
{% if not is_readonly %}
  {{ multiple_classify_form }}

  {% if not user_classification  %}
    <button type="submit" class="btn btn-success">Add classification</button>
    <button type="submit" class="btn btn-success" id="classify-multiple" name="classify_multiple" disabled>Classify multiple</button>
  {% else %}
    <button type="submit" class="btn btn-success">Update classification</button>
    <button type="submit" class="btn btn-success" id="classify-multiple" name="classify_multiple" disabled>Classify multiple</button>
  {% endif %}

  {% if is_project_admin %}
    <button type="submit" class="btn btn-primary" name="approve_classification">Approve classification</button>
    <button type="submit" class="btn btn-primary" id="approve-multiple" name="approve_multiple" disabled>Approve multiple</button>
  {% endif %}
{% endif %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/forms_inline.html
{% load common_tags %}

{% if static_form or dynamic_form %}
  <form action="." method="post" class="form-classificator-rows">
    {% csrf_token %}
    <fieldset>
      <div class="panel panel-default">
        {% if static_form %}
          <div class="panel-heading">
            <h2 class="panel-title">Static attributes</h2>
          </div>

          <table class="table">
            <thead>
            <tr>
              {% for field in static_form %}
                <th {% if field.field.required %}class="form-required"{% endif %}>
                  <span>{{ field.label }}</span>
                </th>
              {% endfor %}
            </tr>
            </thead>

            <tbody>
            <tr>
              {% for field in static_form  %}
                <td>{{ field|as_crispy_non_label_field }}</td>
              {% endfor %}
            </tr>
            </tbody>
          </table>
        {% endif %}

        {% if dynamic_form %}
          <div class="panel-heading">
            <h2 class="panel-title">Dynamic attributes</h2>
          </div>

          <table class="table table-repeatable" data-name="form">
            <thead>
            <tr>
              {% for field in dynamic_form_template %}
              <th {% if field.field.required %}class="form-required"{% endif %}>
                <span>{{ field.label }} {% if field.field.required %}*{% endif %}</span>
              </th>
              {% endfor %}
              <th>Action</th>
            </tr>
            </thead>

            <tbody>
            {% for form in dynamic_form %}
              <tr>
                {% for field in form  %}
                  <td>{{ field|as_crispy_non_label_field }}</td>
                {% endfor %}
                <td>
                  {% if not is_readonly %}
                  <button type="button" class="btn btn-danger btn-remove-row pull-right">
                    <span class="fa fa-remove"></span>
                  </button>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
            </tbody>
            
            {% if not is_readonly %}
            <tfoot>
              <tr>
                <td colspan="100%">
                  <button type="button" class="btn btn-success btn-add-row pull-right"><span class="fa fa-plus"></span></button>
                </td>
              </tr>
            </tfoot>
            {% endif %}

            {{ dynamic_form.management_form }}
          </table>
        {% endif %}
        <div class="panel-footer">
          {% include 'media_classification/classifications/classify/form_button_box.html' %}
        </div>
      </div>
    </fieldset>
  </form>
  <div class="hidden">
    <table class="table">
      <thead>
      </thead>
      <tbody>
        <tr id="dynamic-form-row-template">
          {% for field in dynamic_form_template  %}
          <td>{{ field|as_crispy_non_label_field }}</td>
          {% endfor %}
          <td>
            <button type="button" class="btn btn-danger btn-remove-row pull-right">
              <span class="fa fa-remove"></span>
            </button>
          </td>
        </tr>
      </tbody>
  </div>
{% endif %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/index.html
{% extends "media_classification/index.html" %}

{% load common_tags %}
{% load user_comments %}
{% load crispy_forms_tags %}

{% block data_app %}{% if is_readonly %}classification::preview{% else %}classification::classify{% endif %}{% endblock data_app %}

{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}

<div class="row">
  <div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">
        <span class="fa fa-flask"></span> <a href="{% url 'research:project_detail' pk=project.research_project.pk %}">{{ project.research_project.acronym }}</a> >
        <span class="fa fa-cubes"></span> <a href="{% url 'media_classification:project_detail' pk=project.pk %}">{{ project.name }}</a> >
        <span class="fa fa-database"></span> <a href="{% url 'storage:collection_detail' pk=storage_collection.pk %}">{{ storage_collection.name }}</a> >
        {% if resource.deployment %}
        <span class="fa fa-globe"></span> <a href="{% url 'geomap:deployment_detail' pk=resource.deployment_id %}">{{ resource.deployment }}</a> >
        {% endif %}
        <span class="fa fa-file-{{ resource.get_resource_type_display|lower }}-o"></span> <a href="{% url 'storage:resource_detail' pk=resource.pk %}"><strong>{{ resource.name }}</strong></a>
      </h2>
    </div>
  </div>
</div>
</div>

{% include 'media_classification/classifications/classify/sequence_box.html' %}

<div class="row">
  <div class="col-md-7 media-full">
    {% include 'media_classification/classifications/classify/resource_display.html' %}
  </div>
  
  <div class="col-md-5">
    <div class="panel panel-default">
      
      <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-0" data-toggle="tab">Classifications</a></li>
        <!-- <li><a href="#tab-1" data-toggle="tab">Comments <span class="badge">{% get_comments_count item=project %}</span></a></li> -->
        <!-- <li><a href="#tab-2" data-toggle="tab" id="tab-comment-form"><span class="fa fa-comment"></span> Add a comment</a></li> -->
      </ul>

      <div class="tab-content tab-fixed">
        <div class="tab-pane active" id="tab-0">
          {% include 'media_classification/classifications/classify/classification_box.html' %}
        </div>
        <!-- {% include 'media_classification/classifications/classify/comment_box.html' %} -->
      </div>
    </div>
  </div>
</div>
<h4>Classification forms</h4>
{% if form_template %}
{% include form_template %}
{% endif %}

</div>

{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/resource_box.html
<div class="panel-sequence">
  <img ng-src="{{ resource.get_thumbnail_url }}" class="img-thumbnail">
  <ul>
    <li class="panel-name">
      <span class="fa fa-file-{{ resource.get_resource_type_display|lower }}-o"></span> {{ resource.name }}
    </li>
    <li>Date: {{ resource.date_recorded|date:"d.m.Y" }}</li>
    <li>Time: {{ resource.date_recorded|date:'H:s' }}</li>
  </ul>

  <a class="btn btn-sm btn-block {% if is_classified %}btn-success btn-disabled{% else %}btn-default{% endif %}" href="{% url 'media_classification:classify' project_pk=project.pk collection_pk=collection.pk resource_pk=resource.pk %}">

    <span class="fa fa-eye"></span> Classify
  </a>
</div>

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classify/resource_display.html
{% if resource.resource_type == "V" %}
    <div class="col-md-7 media-full">
        <video
                id="trapper-video-player"
                width="650"
                height="430"
                controls
                preload="auto"
                class="video-js vjs-default-skin">
            <source src="{{ resource.get_url }}" type="{{ resource.mime_type }}"/>
            {% if resource.extra_file %}
                <source src="{{ resource.get_extra_url }}" type="{{ resource.extra_mime_type }}"/>
             {% endif %}
        </video>
        <a href="{{ resource.get_url_original }}" target="_blank">Original file</a>
    </div>
{% elif resource.resource_type == "A" %}
    <audio controls>
        <source src="{{resource.get_url}}" type="{{resource.mime_type}}" />
        {% if resource.extra_file %}
            <source src="{{ resource.get_extra_url }}" type="{{ resource.extra_mime_type }}">
        {% endif %}
    </audio>
{% elif resource.resource_type == "I" %}
    <a href="{{ resource.get_url }}" data-media="image"><img src="{{ resource.get_url }}" alt=""></a>
{% else %}
    Unrecognized resource <type></type>
{% endif %}
 <a href="{{ resource.get_url_original }}" target="_blank">Original file</a>