trapper/trapper-project/trapper/apps/messaging/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from trapper.apps.messaging import views as messaging_views


urlpatterns = [
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('messaging:message_inbox')),
        name='index'
    ),
    url(
        r'message/detail/(?P<hashcode>\w+)/$',
        messaging_views.view_message_detail,
        name='message_detail'
    ),
    url(
        r'message/inbox/$',
        messaging_views.view_message_inbox,
        name='message_inbox'
    ),
    url(
        r'message/outbox/$',
        messaging_views.view_message_outbox,
        name='message_outbox'
    ),
    url(
        r'message/create/$',
        messaging_views.view_message_create,
        name='message_create'
    ),
    url(
        r'collection-request/list/$',
        messaging_views.view_collection_request_list,
        name='collection_request_list'
    ),
    url(
        r'collection-request/resolve/(?P<pk>\d+)/$',
        messaging_views.view_collection_request_resolve,
        name='collection_request_resolve'
    ),
    url(
        r'collection-request/revoke/(?P<pk>\d+)/$',
        messaging_views.view_collection_request_revoke,
        name='collection_request_revoke'
    ),
]

trapper/trapper-project/trapper/apps/research/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from rest_framework.routers import DefaultRouter

from trapper.apps.research.views import api as api_views
from trapper.apps.research.views import research as research_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'research-projects',
    api_views.ResearchProjectViewSet,
    base_name='api-research-project'
)
router.register(
    r'research-project-collections',
    api_views.ResearchProjectCollectionViewSet,
    base_name='api-research-project-collection'
)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('research:project_list')),
        name='project_index'
    ),
]

urlpatterns += [

    url(
        r'project/list/$',
        research_views.view_research_project_list,
        name='project_list'
    ),
    url(
        r'project/detail/(?P<pk>\d+)/$',
        research_views.view_research_project_detail,
        name='project_detail'
    ),
    url(
        r'project/create/$',
        research_views.view_research_project_create,
        name='project_create'
    ),
    url(
        r'project/update/(?P<pk>\d+)/$',
        research_views.view_research_project_update,
        name='project_update'
    ),
    url(
        r'project/delete/(?P<pk>\d+)/$',
        research_views.view_research_project_delete,
        name='project_delete'
    ),
    url(
        r'^project/delete/$',
        research_views.view_research_project_delete,
        name='project_delete_multiple'
    ),
    url(
        r'project/collection/add/$',
        research_views.view_research_project_collection_add,
        name='project_collection_add'
    ),
    url(
        r'^project/collection/delete/$',
        research_views.view_research_project_collection_delete,
        name='project_collection_delete_multiple'
    ),
    url(
        r'^project/collection/delete/(?P<pk>\d+)/$',
        research_views.view_research_project_collection_delete,
        name='project_collection_delete'
    ),
]

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from trapper.apps.accounts.views import accounts as accounts_views

admin.autodiscover()

urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    url(
        r'^account/inactive/$',
        RedirectView.as_view(url=reverse_lazy('trapper_index')),
        name='account_inactive'
    ),
    # Trapper homepage
    url(
        r'^$',
        accounts_views.view_index,
        name='trapper_index'
    ),
    # Media classification urls
    url(
        r'^media_classification/',
        include(
            'trapper.apps.media_classification.urls',
            namespace='media_classification'
        )
    ),
    # Research urls
    url(
        r'^research/',
        include(
            'trapper.apps.research.urls',
            namespace='research'
        )
    ),
    # Storage urls
    url(
        r'^storage/',
        include(
            'trapper.apps.storage.urls',
            namespace='storage'
        )
    ),
    # Messaging urls
    url(
        r'^messaging/',
        include(
            'trapper.apps.messaging.urls',
            namespace='messaging'
        )
    ),
    # Accounts urls
    url(
        '',
        include('django.contrib.auth.urls')
    ),
    url(
        r'^accounts/',
        include(
            'trapper.apps.accounts.urls',
            namespace='accounts'
        )
    ),
    url(
        r'^account/',
        include('allauth.urls')
    ),
    # GeoMap urls
    url(
        r'^geomap/',
        include(
            'trapper.apps.geomap.urls',
            namespace='geomap'
        )
    ),
    # Comments
    url(
        r'^comments/',
        include(
            'trapper.apps.comments.urls',
            namespace='comments'
        )
    ),
    # Sendfile urls
    url(
        r'^serve/',
        include(
            'trapper.apps.sendfile.urls',
            namespace='sendfile'
        )
    ),
    # Forum
    url(
        r'^forum/',
        include(
            'djangobb_forum.urls',
            namespace='djangobb'
        )
    ),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_gis/', include(admin_gis.site.urls)),
    url(r'', include('leaflet_storage.urls')),
    # REST API Swagger docs
    url(r'^docs/api/', include('rest_framework_swagger.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = urlpatterns + [
        url(
            r'^__debug__/', 
            include(debug_toolbar.urls)
        )
    ] + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trapper/trapper-project/trapper/apps/messaging/forms.py
# -*- coding: utf-8 -*-
"""Forms related to Messaging application"""
from __future__ import unicode_literals

from django import forms
from django.contrib.auth import get_user_model

from trapper.apps.messaging.models import Message

User = get_user_model()


class MessageForm(forms.ModelForm):
    """Message form that is used for creating messages to other users.
    This form exclude currently logged in user from list of
    recipients.
    Also sending messages to inactive users is not allowed
    """

    class Meta:
        model = Message
        fields = ['subject', 'text', 'user_to']

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request', None)
        super(MessageForm, self).__init__(*args, **kwargs)
        # exclude inactive users and current user
        user_to_field = self.fields['user_to']
        user_to_field.queryset = User.objects.filter(
            is_active=True
        ).exclude(pk=request.user.pk)
        # select2 classing
        user_to_field.widget.attrs['class'] = 'form-control select2-default'

trapper/trapper-project/trapper/apps/messaging/views.py
# -*- coding: utf-8 -*-
"""Module that contains logic for working with messaging application"""
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.views import generic
from django.shortcuts import redirect
from django.contrib import messages

from braces.views import UserPassesTestMixin

from trapper.apps.messaging.models import (
    Message, CollectionRequest
)
from trapper.apps.messaging.forms import MessageForm
from trapper.apps.messaging.taxonomies import MessageType
from trapper.apps.common.views import HashedDetailView, LoginRequiredMixin


class MessageDetailView(
    LoginRequiredMixin, UserPassesTestMixin, HashedDetailView
):
    """
    View used to show details of given message.
    Before page with message is shown, message is tested if currently logged in
    user have proper rights
    """
    model = Message

    raise_exception = True

    def test_func(self, user):
        """Check if user have enough permissions to display messsage"""
        return self.get_object().can_detail(user=user)

    def get_object(self, *args, **kwargs):
        """Get message by given hashcode and mark it as received"""
        message = super(MessageDetailView, self).get_object(*args, **kwargs)
        message = message.mark_received(user=self.request.user)
        return message

view_message_detail = MessageDetailView.as_view()


class MessageCreateView(LoginRequiredMixin, generic.CreateView):
    """View used for creating new messages"""
    form_class = MessageForm
    template_name = 'messaging/message_create.html'

    def get_form_kwargs(self):
        """Update form `kwargs` so they contain current `request`"""
        kwargs = super(MessageCreateView, self).get_form_kwargs()
        # We need this to exclude current user from receipient list
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        """If form is valid, then :class:`apps.messaging.models.Message`
        `user_from` attribute is updated with currently logged in user, and
        proper message is shown to user"""
        form.instance.user_from = self.request.user
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Message has been sent'
        )
        return super(MessageCreateView, self).form_valid(form)

    def form_invalid(self, form):
        """If form is invalid, then error messages should be shown to user"""
        messages.add_message(
            self.request,
            messages.ERROR,
            'Message form contains errors'
        )
        return super(MessageCreateView, self).form_invalid(form)


view_message_create = MessageCreateView.as_view()


class MessageListView(LoginRequiredMixin, generic.ListView):
    """Base class used for listing currently logged in user messages."""
    model = Message
    context_object_name = 'message_list'
    is_inbox = None
    paginate_by = 20

    def get_context_data(self, **kwargs):
        """Additional information are required to display inbox or outbox
        messages"""
        context = super(MessageListView, self).get_context_data(**kwargs)
        context['is_inbox'] = self.is_inbox
        return context

view_message_list = MessageListView.as_view()


class MessageInboxView(MessageListView):
    """View used to display messages that were sent to currently logged in
    user"""
    template_name = "messaging/message_inbox.html"
    is_inbox = True

    def get_queryset(self):
        """Return all messsages assigned to user"""
        return self.request.user.received_messages.exclude(
            message_type__in=[
                MessageType.COLLECTION_REQUEST,
                MessageType.RESOURCE_REQUEST
            ]
        ).select_related('user_from', 'user_from__userprofile')

view_message_inbox = MessageInboxView.as_view()


class MessageOutboxView(MessageListView):
    """View used to display messages that were sent by currently logged in
    user"""
    template_name = "messaging/message_outbox.html"
    is_inbox = False

    def get_queryset(self):
        """Return all messages that user sent"""
        return self.request.user.sent_messages.all()

view_message_outbox = MessageOutboxView.as_view()


class CollectionRequestListView(LoginRequiredMixin, generic.ListView):
    """View used to display collection requests that were sent to currently
    logged in user"""
    context_object_name = 'collection_requests'
    paginate_by = 20

    model = CollectionRequest
    template_name = 'messaging/collection_request_list.html'

    def get_queryset(self):
        """Return all collection access requests. If request was resolved
        then 'resolve' link will be unavailable"""
        return self.request.user.collection_requests.all().select_related(
            'project', 'message__user_from', 'message__user_from__userprofile'
        ).prefetch_related('collections')

view_collection_request_list = CollectionRequestListView.as_view()


class BaseResolveRequestView(
    LoginRequiredMixin, UserPassesTestMixin, generic.DetailView
):
    """
    Base class that holds logic responsible for resolving access requests
    """
    http_method_names = ['post']
    redirect_url = None

    raise_exception = True

    def test_func(self, user):
        """Resolving is allowed only for recipients of requests"""
        return self.get_object().user == user

    def post(self, request, *args, **kwargs):
        """Approve or reject access to resources or collections"""
        obj = self.get_object()

        is_approved = 'yes' in self.request.POST
        obj.resolve_access(user=request.user, is_approved=is_approved)
        return redirect(reverse(self.redirect_url))


class ResolveCollectionRequestView(BaseResolveRequestView):
    """View used to resolve access to collections requests"""
    model = CollectionRequest
    redirect_url = 'messaging:collection_request_list'

view_collection_request_resolve = ResolveCollectionRequestView.as_view()


class BaseRevokeRequestView(
    LoginRequiredMixin, UserPassesTestMixin, generic.DetailView
):
    """Base class used for revoking access for requests that were approved"""
    http_method_names = ['post']
    redirect_url = None

    raise_exception = True

    def test_func(self, user):
        """Resolving is allowed only for recipients of requests"""
        return self.get_object().user == user

    def post(self, request, *args, **kwargs):
        """Revoke access rights to resources or collections"""
        obj = self.get_object()
        is_revoked = 'yes' in self.request.POST

        if is_revoked:
            obj.resolve_revoke(user=request.user)
        return redirect(reverse(self.redirect_url))


class RevokeCollectionRequestView(BaseRevokeRequestView):
    """View used for revoking access to collections"""
    model = CollectionRequest
    redirect_url = 'messaging:collection_request_list'

view_collection_request_revoke = RevokeCollectionRequestView.as_view()

trapper/trapper-project/trapper/apps/messaging/templates/messaging/collection_request_list.html
{% extends "messaging/index.html" %}

{% block messaging_collection_request %}primary{% endblock %}
{% block data_app %}message::preview{% endblock %}

{% block section_content %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">Messages</h2>
    </div>

    {% if collection_requests %}
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Sender</th>
        <th>Message</th>
        <th>Research project</th>
        <th>Collection</th>
        <th>Action</th>
      </tr>
      </thead>

      <tbody>
      {% for collection_request in collection_requests %}
        <tr>
          <td><a href="{{ collection_request.message.user_from.userprofile.get_absolute_url }}">{% pretty_username collection_request.message.user_from %}</a></td>
          <td>
            <span class="fa fa-circle{% if not collection_request.message.is_new %}-o{% endif %}"></span>
            <a href="{{ collection_request.message.get_absolute_url }}" >View Message
            </a>
          </td>
          {% with collection_request.project as project %}
            <td>
              <a href="{% url "research:project_detail" project.pk %}">{{ project.name }}</a></td>
          {% endwith %}
          <td>
            {% for collection in collection_request.collections.all %}
              <a href="{% url "storage:collection_detail" collection.pk %}">{{ collection.name }}</a>
            {% endfor %}
          </td>

          <td>
            {% if collection_request.resolved_at %}
              {% if collection_request.is_approved %}<b class="text-green">Approved</b>{% else %}<b class="text-red">Rejected</b>{% endif %} at {{ collection_request.resolved_at|date:"d.m.Y, H:i" }}
            {% else %}
              <button type="button" class="btn btn-link" data-resolve="{% url 'messaging:collection_request_resolve' collection_request.pk %}" data-type="collection">Resolve</button>
            {% endif %}
            {% if collection_request.is_approved %}
              <p><button type="button" class="btn btn-link" data-revoke="{% url 'messaging:collection_request_revoke' collection_request.pk %}" data-type="collection">Revoke</button></p>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% include 'common/pagination.html' %}

    {% else %}
      <div class="alert alert-warning ng-binding">
        <span class="fa fa-info"></span> No collection requests available.
      </div>

    {% endif %}
  </div>

{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/index.html
{% extends "index.html" %}

{% load common_tags %}

{% block data_app %}messaging:main{% endblock %}

{% block main_menu %}{% nav_active 'menu_messages' %}{{ block.super }}{% endblock main_menu %}

{% block content %}
  <ul class="nav nav-pills">
    <div class="nav-secondary">
      <a href="{% url "messaging:message_inbox" %}" class="btn btn-{% block messaging_message_inbox %}default{% endblock %}">Inbox <span class="badge">{{ user.userprofile.count_unread_messages }}/{{ user.userprofile.count_inbox_messages }}</span></a>
      <a href="{% url "messaging:message_outbox" %}" class="btn btn-{% block messaging_message_outbox %}default{% endblock %}">Outbox <span class="badge">{{ user.sent_messages.all.count }}</span></a>
      <a href="{% url "messaging:collection_request_list" %}" class="btn btn-{% block messaging_collection_request %}default{% endblock %}">Collection requests <span class="badge">{{ user.userprofile.awaiting_collection_requests }}</span></a>
      <a href="{% url "messaging:message_create" %}" class="btn btn-success pull-right"><span class="fa fa-pencil"></span> New message</a>
    </div>

  </ul>
  <div class="pill-content">
    {% block section_content %}{% endblock section_content %}
  </div>
{% endblock content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_create.html
{% extends "messaging/index.html" %}
{% block messaging_message_create %}primary{% endblock %}
{% block data_app %}message::new{% endblock %}

{% block section_content %}
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">New message</h2>
      </div>

      <form action="." method="post" class="panel-body">
        {% csrf_token %}
        <fieldset>
          <div class="form-group form-required">
            <label for="{{ form.subject.name }}" class="control-label">Subject</label>
            <input type="text" class="form-control" id="id_{{form.subject.name}}" name="{{form.subject.name}}" placeholder="Subject" required>
          </div>

          <div class="form-group form-required">
            <label for="{{ form.user_to.name }}" class="control-label">Recipent</label>
            {{ form.user_to }}
          </div>

          <div class="form-group form-required">
            <label for="{{ form.text.name }}" class="control-label">Message</label>
            <textarea id="id_{{ form.text.name }}" name="{{ form.text.name }}" class="form-control textarea-wysiswyg" rows="10"></textarea>
          </div>

          <button type="submit" class="btn btn-primary">Send</button>
        </fieldset>
      </form>
    </div>
  </div>


{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_detail.html
{% extends "messaging/index.html" %}

{% block messaging_message_inbox %}{% if message.is_inbox %}primary{% else %}default{% endif %}{% endblock %}
{% block messaging_message_outbox %}{% if message.is_outbox %}primary{% else %}default{% endif %}{% endblock %}
{% block messaging_collection_request %}{% if message.is_collection_request %}primary{% else %}default{% endif %}{% endblock %}
{% block messaging_resource_request %}{% if message.is_resource_request %}primary{% else %}default{% endif %}{% endblock %}

{% block data_app %}message::preview{% endblock %}

{% block section_content %}
  {% with message.user_from as sender %}
  {% with sender.userprofile.get_absolute_url as sender_profile %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">Title: <strong>{{ message.subject|safe }}</strong></h2>
    </div>

    <div class="panel-body">
      {{ message.text|safe}}
    </div>

    <div class="panel-footer">
      Sender: <strong><a href="{{ sender_profile }}">{% pretty_username sender %}</a></strong>
    </div>
    <div class="panel-footer">
      Date: <strong>{{ message.date_sent|date:"d.m.Y, H:i" }}</strong>
    </div>
  </div>

  {% endwith %}
  {% endwith %}
{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_inbox.html
{% extends "messaging/index.html" %}

{% block messaging_message_inbox %}primary{% endblock %}
{% block data_app %}message::list{% endblock %}

{% block section_content %}
  {% include "messaging/message_list.html" %}
{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_list.html
<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Messages</h2>
  </div>

  {% if message_list %}
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Subject</th>
      <th>Date</th>
      <th>Sender</th>
    </tr>
    </thead>

    <tbody>
    {% for message in message_list %}
    <tr>
      <td>
        <span class="fa fa-circle{% if not is_inbox or not message.is_new %}-o{% endif %}"></span>
        <a href="{% url "messaging:message_detail" message.hashcode %}">{{ message.subject|safe }}</a>
      </td>
      <td>{{ message.date_sent|date:"d.m.Y, H:i" }}</td>
      <td><a href="{{ message.user_from.userprofile.get_absolute_url }}">{% pretty_username message.user_from %}</a></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
  {% include 'common/pagination.html' %}
  {% else %}
    <div class="alert alert-warning ng-binding">
      <span class="fa fa-info"></span> No messages available.
    </div>
  {% endif %}
</div>

trapper/trapper-project/trapper/apps/messaging/templates/messaging/message_outbox.html
{% extends "messaging/index.html" %}

{% block messaging_message_outbox %}primary{% endblock %}
{% block data_app %}message::list{% endblock %}

{% block section_content %}
  {% include "messaging/message_list.html" %}
{% endblock section_content %}

trapper/trapper-project/trapper/apps/messaging/templates/messaging/resource_request_list.html
{% extends "messaging/index.html" %}

{% block messaging_resource_request %}primary{% endblock %}
{% block data_app %}message::preview{% endblock %}

{% block section_content %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">Messages</h2>
    </div>

    {% if resource_requests %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Sender</th>
          <th>Message</th>
          <th>Resource</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
      {% for resource_request in resource_requests %}
        <tr>
          <td><a href="{{ resource_request.message.user_from.userprofile.get_absolute_url }}">{% pretty_username resource_request.message.user_from %}</a></td>
          <td><a href="{{ resource_request.message.get_absolute_url }}" >View Message</a></td>
          <td>
            {% for resource in resource_request.resources.all %}
              <a href="{% url "storage:resource_detail" resource.pk %}">{{ resource.name }}</a>
            {% endfor %}
          </td>

          <td>
            {% if resource_request.resolved_at %}
              {% if resource_request.is_approved %}<b class="text-green">Approved</b>{% else %}<b class="text-red">Rejected</b>{% endif %} at {{ resource_request.resolved_at|date:"d.m.Y, H:i" }}
            {% else %}
              <button type="button" class="btn btn-link" data-resolve="{% url 'messaging:resource_request_resolve' resource_request.pk %}" data-type="collection">Resolve</button>
            {% endif %}
            {% if resource_request.is_approved %}
            <p><button type="button" class="btn btn-link" data-revoke="{% url 'messaging:resource_request_revoke' resource_request.pk %}" data-type="collection">Revoke</button></p>
            {% endif %}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    {% include 'common/pagination.html' %}

    {% else %}
      <div class="alert alert-warning ng-binding">
        <span class="fa fa-info"></span> No resource requests available.
      </div>
    {% endif %}
  </div>

{% endblock section_content %}