trapper/trapper-project/trapper/apps/geomap/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.views.decorators.cache import never_cache

from leaflet_storage.utils import decorated_patterns
from leaflet_storage.decorators import map_permissions_check
from leaflet_storage import views as ls_views

from rest_framework.routers import DefaultRouter

from trapper.apps.geomap.views import api as api_views
from trapper.apps.geomap.views import map as map_views
from trapper.apps.geomap.views import location as location_views
from trapper.apps.geomap.views import deployment as deployment_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'locations',
    api_views.LocationViewSet,
    base_name='api-location'
)

router.register(
    r'deployments',
    api_views.DeploymentViewSet,
    base_name='api-deployment'
)

router.register(
    r'maps',
    api_views.MapViewSet,
    base_name='api-map'
)

urlpatterns = [
    url(
        r'^api/locations/export/$',
        api_views.LocationTableView.as_view(),
        name='api-location-export'
    ),
    url(
        r'^api/deployments/export/$',
        api_views.DeploymentTableView.as_view(),
        name='api-deployment-export'
    ),
    url(
        r'^api/locations/geojson/$',
        api_views.LocationGeoViewSet.as_view(),
        name='api-location-geojson'
    ),
    url(r'^api/', include(router.urls))
]

urlpatterns += [

    url(
        r'^location/bulk-update/$',
        location_views.view_location_bulk_update,
        name='location_bulk_update'
    ),
    url(
        r'^location/create/$',
        RedirectView.as_view(url=u'/geomap/map/?action=create'),
        name='location_create'
        ),
    url(
        r'^location/(?P<pk>\d+)/delete/$',
        location_views.view_location_delete,
        name='location_delete'
    ),
    url(
        r'^location/delete/$',
        location_views.view_location_delete,
        name='location_delete_multiple'
    ),
    url(r'^location/list/$',
        location_views.view_location_list,
        name='location_list'
    ),
    url(
        r'^location/import/$',
        location_views.view_location_import,
        name='location_import'
    ),
    url(
        r'^location/filterform/$',
        location_views.view_location_filter_form,
        name="locations_filterform"
    ),
    url(
        r'^location/createform/$',
        location_views.view_location_create_form,
        name="locations_createform"
    ),
    url(
        r'^location/(?P<pk>\d+)/editform/$',
        location_views.view_location_edit_filter_form,
        name="locations_editform"
    ),
    url(
        r'^location/collections/$',
        location_views.view_location_collections,
        name="location_collections"
    ),
]

urlpatterns += [

    url(
        r'^map/permissions/update/(?P<map_id>[\d]+)/$',
        map_views.view_update_map_permissions,
        name="map_permissions"
    ),
    url(
        r'^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$',
        map_views.view_map, 
        name='map'
    ),
    url(
        r'^map/list/$', 
        map_views.view_map_list, 
        name="map_list"),
    url(
        r'^map/(?P<pk>\d+)/delete/$',
        map_views.view_map_delete,
        name='map_delete'
    ),
    url(
        r'^map/delete/$',
        map_views.view_map_delete,
        name='map_delete_multiple'
    ),
    url(
        r'^map/$', 
        map_views.view_new_map, 
        name='map_view'
    ),
    url(
        r'permissions/update/(?P<map_id>\d+)/$',
        map_views.view_update_map_permissions,
        name='map_permissions'
    ),
    url(
        r'^map/create/$', 
        map_views.view_map_create, 
        name='map_create'
    ),
]

urlpatterns += [
    url(r'^map/(?P<map_id>[\d]+)/update/settings/$',
        ls_views.MapUpdate.as_view(), name='map_update'),
    url(r'^map/(?P<map_id>[\d]+)/update/permissions/$',
        ls_views.UpdateMapPermissions.as_view(),
        name='map_update_permissions'),
    url(r'^map/(?P<map_id>[\d]+)/update/delete/$',
        ls_views.MapDelete.as_view(), name='map_delete'),
    url(r'^map/(?P<map_id>[\d]+)/update/clone/$',
        ls_views.MapClone.as_view(), name='map_clone'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/create/$',
        ls_views.DataLayerCreate.as_view(), name='datalayer_create'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$',
        ls_views.DataLayerUpdate.as_view(), name='datalayer_update'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$',
        ls_views.DataLayerDelete.as_view(), name='datalayer_delete'),
]

urlpatterns += [

    # Deployments
    url(
        r'^deployment/$',
        RedirectView.as_view(url=reverse_lazy('geomap:deployment_list')),
        name='deployment_index'
    ),
    url(
        r'^deployment/list/$',
        deployment_views.view_deployment_list,
        name='deployment_list'
    ),
    url(
        r'^deployment/detail/(?P<pk>\d+)/$',
        deployment_views.view_deployment_detail,
        name='deployment_detail'
    ),
    url(
        r'^deployment/delete/(?P<pk>\d+)/$',
        deployment_views.view_deployment_delete,
        name='deployment_delete'
    ),
    url(
        r'^deployment/delete/$',
        deployment_views.view_deployment_delete,
        name='deployment_delete_multiple'
    ),
    url(
        r'^deployment/create/$',
        deployment_views.view_deployment_create,
        name='deployment_create'
    ),
    url(
        r'^deployment/update/(?P<pk>\d+)/$',
        deployment_views.view_deployment_update,
        name='deployment_update'
    ),
    url(
        r'^deployment/bulk-update/$',
        deployment_views.view_deployment_bulk_update,
        name='deployment_bulk_update'
    ),
    url(
        r'^deployment/bulk-create/$',
        deployment_views.view_deployment_bulk_create,
        name='deployment_bulk_create'
    ),
    url(
        r'deployment/import/$',
        deployment_views.view_deployment_import,
        name='deployment_import'
    ),
]

trapper/trapper-project/trapper/apps/media_classification/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from trapper.apps.media_classification.views import (
    api as classification_api_views
)
from trapper.apps.media_classification.views import (
    classifications as classifications_views,
    user_classifications as user_classifications_views,
    projects as projects_views,
    classificators as classificators_views,
    sequences as sequences_views 
)


router = DefaultRouter(trailing_slash=False)

router.register(
    r'classificators',
    classification_api_views.ClassificatorViewSet,
    base_name='api-classificator'
)

router.register(
    r'user-classifications',
    classification_api_views.UserClassificationViewSet,
    base_name='api-user-classification'
)

router.register(
    r'classifications',
    classification_api_views.ClassificationViewSet,
    base_name='api-classification'
)

router.register(
    r'classifications_map',
    classification_api_views.ClassificationMapViewSet,
    base_name='api-classification-map'
)

router.register(
    r'classification-projects',
    classification_api_views.ClassificationProjectViewSet,
    base_name='api-classification-project'
)

router.register(
    r'classification-project-collections',
    classification_api_views.ClassificationProjectCollectionViewSet,
    base_name='api-classification-project-collection'
)

router.register(
    r'sequences',
    classification_api_views.SequenceViewSet,
    base_name='api-sequence'
)

router.register(
    r'classification/(?P<collection_pk>\d+)/(?P<current_resource_pk>\d+)/resources/$',
    classification_api_views.ClassificationResourcesViewSet,
    base_name='api-classification-resources'
)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(
        r'^api/classifications/results/(?P<project_pk>\d+)/',
        classification_api_views.ClassificationResultsView.as_view(),
        name='api-classification-results'
    ),
    url(
        r'^api/classifications/results/agg/(?P<project_pk>\d+)/',
        classification_api_views.ClassificationResultsAggView.as_view(),
        name='api-classification-results-agg'
    ),
    url(
        r'^api/classifications/import',
        classification_api_views.ClassificationImport.as_view(),
        name='api-classification-import'
    )
]

urlpatterns += [

    url(
        r'^$',
        RedirectView.as_view(
            url=reverse_lazy('media_classification:project_list')
        ),
        name='project_index'
    ),

    # Project views
    url(
        r'project/list/$',
        projects_views.view_project_list, 
        name='project_list'
    ),
    url(
        r'project/detail/(?P<pk>\d+)/$',
        projects_views.view_project_detail,
        name='project_detail'
    ),

    url(
        r'project/create/$', 
        projects_views.view_project_create,
        name='project_create'
    ),
    url(
        r'project/update/(?P<pk>\d+)/$', 
        projects_views.view_project_update,
        name='project_update'
    ),
    url(
        r'project/delete/(?P<pk>\d+)/$',
        projects_views.view_project_delete,
        name='project_delete'
    ),
    url(
        r'^project/delete/$',
        projects_views.view_project_delete,
        name='project_delete_multiple'
    ),
    url(
        r'project/collection/add/$',
        projects_views.view_project_collection_add,
        name='project_collection_add'
    ),
    url(
        r'project/collection/delete/(?P<pk>\d+)/$',
        projects_views.view_project_collection_delete,
        name='project_collection_delete'
    ),
    url(
        r'^project/collection/delete/$',
        projects_views.view_project_collection_delete,
        name='project_collection_delete_multiple'
    ),

    # Classificator views
    url(
        r'classificator/list/$', 
        classificators_views.view_classificator_list,
        name='classificator_list'
    ),
    url(
        r'classificator/detail/(?P<pk>\d+)/$',
        classificators_views.view_classificator_detail, 
        name='classificator_detail'
    ),

    url(
        r'classificator/create/$', 
        classificators_views.view_classificator_create,
        name='classificator_create'
    ),
    url(
        r'classificator/update/(?P<pk>\d+)/$',
        classificators_views.view_classificator_update,
        name='classificator_update'
    ),
    url(
        r'classificator/clone/(?P<pk>\d+)/$',
        classificators_views.view_classificator_clone,
        name='classificator_clone'
    ),
    url(
        r'^classificator/delete/(?P<pk>\d+)/$',
        classificators_views.view_classificator_delete,
        name='classificator_delete'
    ),
    url(
        r'^classificator/delete/$',
        classificators_views.view_classificator_delete,
        name='classificator_delete_multiple'
    ),

    # Sequence views
    url(
        r'sequence/create/$',
        sequences_views.view_sequence_change,
        name='sequence_create'
    ),
    url(
        r'sequence/update/$',
        sequences_views.view_sequence_change,
        name='sequence_update'
    ),
    url(
        r'sequence/change/$',
        sequences_views.view_sequence_change,
        name='sequence_change'
    ),
    url(
        r'sequence/delete/$',
        sequences_views.view_sequence_delete,
        name='sequence_delete'
    ),
    url(
        r'^sequence/build/$',
        sequences_views.view_sequence_build,
        name='sequence_build'
    ),

    # Classification views
    url(
        r'classification/detail/(?P<pk>\d+)/$',
        classifications_views.view_classification_detail,
        name='classification_detail'
    ),
    url(
        r'^classification/list/(?P<pk>\d+)/$',
        classifications_views.view_classification_list,
        name='classification_list'
    ),
    url(
        r'classification/import/$',
        classifications_views.view_classification_import,
        name='classification_import'
    ),
    url(
        r'classification/import/(?P<pk>\d+)/$',
        classifications_views.view_classification_import,
        name='classification_import'
    ),
    url(
        r'classification/export/(?P<pk>\d+)/$',
        classifications_views.view_classification_export,
        name='classification_export'
    ),
    url(
        r'classification/form/(?P<pk>\d+)/$',
        classifications_views.view_classification_tag,
        name='classification_tag'
    ),
    url(
        r'classification/delete/(?P<pk>\d+)/$',
        classifications_views.view_classification_delete,
        name='classification_delete'
    ),
    url(
        r'classification/delete/$',
        classifications_views.view_classification_delete,
        name='classification_delete_multiple'
    ),
    url(
        r'classify/(?P<project_pk>\d+)/(?P<collection_pk>\d+)/$',
        classifications_views.view_classify_collection,
        name='classify_collection'
    ),
    url(
        r'classify/(?P<pk>\d+)/$',
        classifications_views.view_classify_resource,
        name='classify'
    ),
    url(
        r'classify/(?P<pk>\d+)/user/(?P<user_pk>\d+)/$',
        classifications_views.view_classify_resource,
        name='classify_user'
    ),
    url(
        r'classify/approve/(?P<pk>\d+)/$',
        classifications_views.view_classify_approve,
        name='classify_approve'
    ),

    # UserClassification views
    url(
        r'user_classification/list/(?P<pk>\d+)/$',
        user_classifications_views.view_user_classification_list,
        name='user_classification_list'
    ),
    url(
        r'user_classification/approve/(?P<pk>\d+)/$',
        user_classifications_views.view_user_classification_bulk_approve,
        name='user_classification_bulk_approve'
    )

]

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from trapper.apps.accounts.views import accounts as accounts_views

admin.autodiscover()

urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    url(
        r'^account/inactive/$',
        RedirectView.as_view(url=reverse_lazy('trapper_index')),
        name='account_inactive'
    ),
    # Trapper homepage
    url(
        r'^$',
        accounts_views.view_index,
        name='trapper_index'
    ),
    # Media classification urls
    url(
        r'^media_classification/',
        include(
            'trapper.apps.media_classification.urls',
            namespace='media_classification'
        )
    ),
    # Research urls
    url(
        r'^research/',
        include(
            'trapper.apps.research.urls',
            namespace='research'
        )
    ),
    # Storage urls
    url(
        r'^storage/',
        include(
            'trapper.apps.storage.urls',
            namespace='storage'
        )
    ),
    # Messaging urls
    url(
        r'^messaging/',
        include(
            'trapper.apps.messaging.urls',
            namespace='messaging'
        )
    ),
    # Accounts urls
    url(
        '',
        include('django.contrib.auth.urls')
    ),
    url(
        r'^accounts/',
        include(
            'trapper.apps.accounts.urls',
            namespace='accounts'
        )
    ),
    url(
        r'^account/',
        include('allauth.urls')
    ),
    # GeoMap urls
    url(
        r'^geomap/',
        include(
            'trapper.apps.geomap.urls',
            namespace='geomap'
        )
    ),
    # Comments
    url(
        r'^comments/',
        include(
            'trapper.apps.comments.urls',
            namespace='comments'
        )
    ),
    # Sendfile urls
    url(
        r'^serve/',
        include(
            'trapper.apps.sendfile.urls',
            namespace='sendfile'
        )
    ),
    # Forum
    url(
        r'^forum/',
        include(
            'djangobb_forum.urls',
            namespace='djangobb'
        )
    ),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_gis/', include(admin_gis.site.urls)),
    url(r'', include('leaflet_storage.urls')),
    # REST API Swagger docs
    url(r'^docs/api/', include('rest_framework_swagger.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = urlpatterns + [
        url(
            r'^__debug__/', 
            include(debug_toolbar.urls)
        )
    ] + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/change.html
{% extends "media_classification/index.html" %}

{% load common_tags %}
{% load crispy_forms_tags %}

{% block data_app %}classification::create{% endblock data_app %}
{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}
    <div class="container">

        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">{% if object %}Update{% else %}Add{% endif %} classification project</h2>
                </div>


                <form action="." class="panel-body" method="post">
                    {% crispy form form.helper %}
                    <fieldset>
                        <button type="submit" class="btn btn-primary">{% if object %}Update{% else %}Add{% endif %}
                            classification project
                        </button>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>

{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/detail.html
{% extends "media_classification/index.html" %}

{% load common_tags %}

{% block data_app %}classification{% endblock %}
{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}

  <div
    class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Classification project</h2>
          </div>

          <div class="panel-body">
            <h2>{{ project.name }}</h2>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Research project</h2>
          </div>

          <div class="panel-body">
            <h2><span class="fa fa-flask"></span> <a href="{% url 'research:project_detail' pk=project.research_project.pk %}">{{ project.research_project.acronym }}</a></h2>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Flags</h2>
          </div>
            <div class="panel-body">
                <label class="control-label">Sequences:</label>
                <span class="label label-default">{{ project.enable_sequencing }}</span>,
                <label class="control-label">Crowdsourcing:</label>
                <span class="label label-default">{{ project.enable_crowdsourcing }}</span>,
                <label class="control-label">Status:</label>
                <span class="label label-default">{{ project.get_status_display }}</span>
            </div>
        </div>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Actions</h2>
          </div>
            <div class="panel-body">
                {% if project.can_update %}
                <a href="{% url "media_classification:project_update" project.pk %}" 
                   class="btn btn-default" role="button">
                  <span class="fa fa-pencil"></span> Update
                </a>
                <a href="{% url "media_classification:classification_import" project.pk %}" 
                   class="btn btn-default" role="button">
                  <span class="fa fa-upload"></span> Import results
                </a>
                <a href="{% url "media_classification:classification_export" project.pk %}"
                   class="btn btn-default" role="button">
                  <span class="fa fa-download"></span> Export results
                </a>
                {% endif %}
            </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h2 class="panel-title">Project results</h2>
          </div>

	  <div class="panel-body">
            <div class="row">
              <div class="col-md-6">
                <ul class="list-group list-group-rich">
                  {% with project.get_classification_stats as stats %}
                  <li class="list-group-item"><span class="list-group-label" title="Number of resources with approved classification">Approved:</span>  <strong>{{ stats.approved }}</strong></li>
                  <li class="list-group-item"><span class="list-group-label" title="Number of resources with classification (including approved classifications)">Classified:</span>  <strong>{{ stats.classified }}</strong></li>
                  <li class="list-group-item"><span class="list-group-label" title="Number of resources without classification">Unclassified:</span> <strong>{{ stats.unclassified }}</strong></li>
                  {% endwith %}
                </ul>
              </div>
              <div class="col-md-6">
	        <h4><span class="fa fa-eye"></span> <a href="{% url 'media_classification:classification_list' pk=project.pk %}">See classification results</a></h4>
                <h4><span class="fa fa-eye"></span> <a href="{% url 'media_classification:user_classification_list' pk=project.pk %}"> See users' classifications</a></h4>
	      </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading collapsable">
        <h2 class="panel-title">
          Users in the project
        </h2>
      </div>
      {% with project.get_user_roles_with_profiles as project_roles %}
        {% if project_roles %}
          <table class="table table-striped table-rich">
            <thead>
            <tr>
              <th></th>
              <th>User</th>
              <th>Role</th>
              <th>E-mail</th>
              <th>Institution</th>
            </tr>
            </thead>

            <tbody>
            {% for role in project_roles %}
              {% with role.user.userprofile as user_profile %}
                <tr>
                  <td>
                    <a href="{% url 'accounts:show_profile' role.user %}"><img src="{{ user_profile.avatar_url }}" alt="{{ role.user.username }}" class="img-thumbnail avatar-small" style="display:inline"></a>
                  </td>
                  <td><a href="{% url 'accounts:show_profile' role.user %}">{{ role.user|pretty_username }}</a></td>
                  <td>{{ role.get_name_display }}</td>
                  <td><a href="mailto:{{role.user.email}}">{{ role.user.email|default:"" }}</a></td>
                  <td>{{ user_profile.institution|default:"" }}</td>
              {% endwith %}
            {% endfor %}

            </tbody>
          </table>
        {% endif %}
      {% endwith %}
    </div>
  </div>

  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Classificator</h2>
      </div>
      <div class="panel-body">
        {% if project.classificator %}
        <a href="{% url 'media_classification:classificator_detail' pk=project.classificator.pk %}">{{ project.classificator.name }}</a>
        {% else %}
        There is no classificator assigned to this project.
        {% endif %}
      </div>
    </div>
  </div>

  <h2 class="container">Collections</h2>
  {% with grid_context=collection_context %}
  {% include 'media_classification/projects/detail_collection_grid.html' %}
  {% endwith %}

{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/detail_collection_grid.html
{% extends "common/grid.html" %}

{% block filters %}

<div class="form-group form-filter">
  <label for="status" class="control-label">Status</label>
  <select
     id="status"
     class="form-control"
     filter-text="status"
     filter-service="filter"
     ng-model="filters.status"
     ng-options="option.value as option.label for option in optionList.status">
  </select>
</div>

<div class="form-group form-filter">
  <label for="status" class="control-label">Active</label>
  <select
     id="is_active"
     class="form-control"
     filter-text="is_active"
     filter-service="filter"
     ng-model="filters.is_active"
     ng-options="option.value as option.label for option in optionList.bool">
  </select>
</div>

<div class="form-group form-filter-full">
  <label for="owners" class="control-label">Owners</label>
  <select
     type="text"
     id="owners"
     class="select2-default"
     multiple
     ng-model="filters.owners"
     filter-tokens="owner"
     filter-service="filter">
    {% for owner in grid_context.owners %}
    <option value="{{ owner.pk }}">{{ owner|pretty_username }}</option>
    {% endfor %}
  </select>
</div>

{% endblock %}

{% block custom_actions %}

{% if not grid_context.hide_show_on_map %}
{% url 'geomap:map_view' as new_map_url %}
<action-show-map data-type="collections" data-url="{{ new_map_url }}"
                 data-field="collection_pk">
  <select>
    <option value="{{ new_map_url }}" selected>New map</option>
    {% for map in grid_context.maps %}
    <option value="{% url 'geomap:map' slug=map.slug pk=map.pk %}">{{ map }}</option>
    {% endfor %}
  </select>
</action-show-map>
{% endif %}

{% if user.is_authenticated and project.can_update %}
<action-build-sequences ng-disabled="!data.selectedCounter" ng-click="execute('{% url "media_classification:sequence_build" %}')">
</action-build-sequences>
{% endif %}

{% endblock%}

{% block custom_actions_list %}

{% if user.is_authenticated and project.can_update %}
<li>
  <action-unlink2-selected ng-click="execute($event, '{% url "media_classification:project_collection_delete_multiple" %}')">
  </action-unlink2-selected>
</li>
{% endif %}

{% endblock %}

{% block table_cells %}

<td data-title="'Name'" sortable="'name'">{[{ record.name }]}</td>
<td data-title="'Status'" sortable="'status'">{[{ record.status }]}</td>
<td data-title="'Is active'" sortable="'is_active'">{[{ record.is_active }]}</td>
<!-- <td data-title="'Crowdsourcing'" sortable="'crowdsourcing'">{[{ record.crowdsourcing }]}</td> -->
<td data-title="'Total'">{[{ record.total_count }]}</td>
<td data-title="'Classified'">{[{ record.classified_count }]}</td>
<td data-title="'Approved'">{[{ record.approved_count }]}</td>

{% endblock %}

{% block table_cells_extra_actions %}
</td>
<td>
  <action-classify-collection 
     ng-if="record.classify_data"
     ng-click="execute($event, record)">
  </action-classify-collection>

{% if project.deployment_based_nav %}
  <select
     placeholder="choose deployments (optionally)"
     class="select2-default"
     style="width:260px"
     multiple
     ng-model="filters.deployments[record.pk]"
     filter-service="filter"
     filter-tokens="deployment"
     ng-if="record.classify_data"
     ng-options="option[0] as option[1] for option in record.deployments">
  </select>
{% endif %}
</td>
{% endblock %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/form_inline.html
<div class="form-inline">

    <div class="checkbox-inline">
        <label>
            {{ form.deployment_based_nav }}
            Deployment-based navigation
        </label>
    </div>

    <div class="checkbox-inline">
        <label>
            {{ form.enable_sequencing }}
            Sequences
        </label>
    </div>

    <div class="checkbox-inline">
        <label>
            {{ form.enable_crowdsourcing }}
            Crowdsourcing
        </label>
    </div>

</div>

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/grid.html
{% extends "common/grid.html" %}

{% block filters %}

<div class="form-group form-filter">
  <label for="status" class="control-label">Progress</label>
  <select
     id="status"
     class="form-control"
     filter-text="status"
     filter-service="filter"
     ng-model="filters.status"
     ng-options="option.value as option.label for option in optionList.progress">
  </select>
</div>

{% endblock %}

{% block custom_actions %}
{% endblock%}

{% block custom_actions_list %}

<li ng-class="{'disabled': !filters.owner}">
  <action-remove-selected ng-click="execute($event, '{% url "media_classification:project_delete_multiple" %}')">
  </action-remove-selected>
</li>

{% endblock%}

{% block exclude_column_headers %}
{% if grid_context.hide_research_project_col %}
ng-if="column != 'Research project'"
{% endif %}
{% endblock %}

{% block table_cells %}

<td data-title="'Name'" sortable="'name'">{[{ record.name }]}</td>

{% if not grid_context.hide_research_project_col %}
<td data-title="'Research project name'" sortable="'research_project'">{[{ record.research_project }]}</td>
{% endif %}
<td data-title="'Status'" sortable="'status'">{[{ record.status }]}</td>

{% endblock %}

{% block table_cells_extra_actions %}

<action-warning ng-if="!record.classificator" ng-click="execute($event, 'This classification project has no classificator assigned', record)"></action-warning>

{% endblock %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/list.html
{% extends "media_classification/index.html" %}

{% load common_tags %}

{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}
    {% with grid_context=classification_project_context %}
    {% include 'media_classification/projects/grid.html' %}
    {% endwith %}
{% endblock section_content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/projects/sequence_build_form.html
{% load crispy_forms_tags %}

<form action="." method="post" class="panel-body">
    {% crispy form form.helper %}
    <fieldset>
        <button type="submit" class="btn btn-primary">(Re)build sequences</button>
    </fieldset>
</form>