trapper/trapper-project/trapper/apps/geomap/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.views.decorators.cache import never_cache

from leaflet_storage.utils import decorated_patterns
from leaflet_storage.decorators import map_permissions_check
from leaflet_storage import views as ls_views

from rest_framework.routers import DefaultRouter

from trapper.apps.geomap.views import api as api_views
from trapper.apps.geomap.views import map as map_views
from trapper.apps.geomap.views import location as location_views
from trapper.apps.geomap.views import deployment as deployment_views


router = DefaultRouter(trailing_slash=False)
router.register(
    r'locations',
    api_views.LocationViewSet,
    base_name='api-location'
)

router.register(
    r'deployments',
    api_views.DeploymentViewSet,
    base_name='api-deployment'
)

router.register(
    r'maps',
    api_views.MapViewSet,
    base_name='api-map'
)

urlpatterns = [
    url(
        r'^api/locations/export/$',
        api_views.LocationTableView.as_view(),
        name='api-location-export'
    ),
    url(
        r'^api/deployments/export/$',
        api_views.DeploymentTableView.as_view(),
        name='api-deployment-export'
    ),
    url(
        r'^api/locations/geojson/$',
        api_views.LocationGeoViewSet.as_view(),
        name='api-location-geojson'
    ),
    url(r'^api/', include(router.urls))
]

urlpatterns += [

    url(
        r'^location/bulk-update/$',
        location_views.view_location_bulk_update,
        name='location_bulk_update'
    ),
    url(
        r'^location/create/$',
        RedirectView.as_view(url=u'/geomap/map/?action=create'),
        name='location_create'
        ),
    url(
        r'^location/(?P<pk>\d+)/delete/$',
        location_views.view_location_delete,
        name='location_delete'
    ),
    url(
        r'^location/delete/$',
        location_views.view_location_delete,
        name='location_delete_multiple'
    ),
    url(r'^location/list/$',
        location_views.view_location_list,
        name='location_list'
    ),
    url(
        r'^location/import/$',
        location_views.view_location_import,
        name='location_import'
    ),
    url(
        r'^location/filterform/$',
        location_views.view_location_filter_form,
        name="locations_filterform"
    ),
    url(
        r'^location/createform/$',
        location_views.view_location_create_form,
        name="locations_createform"
    ),
    url(
        r'^location/(?P<pk>\d+)/editform/$',
        location_views.view_location_edit_filter_form,
        name="locations_editform"
    ),
    url(
        r'^location/collections/$',
        location_views.view_location_collections,
        name="location_collections"
    ),
]

urlpatterns += [

    url(
        r'^map/permissions/update/(?P<map_id>[\d]+)/$',
        map_views.view_update_map_permissions,
        name="map_permissions"
    ),
    url(
        r'^map/(?P<slug>[-_\w]+)_(?P<pk>\d+)$',
        map_views.view_map, 
        name='map'
    ),
    url(
        r'^map/list/$', 
        map_views.view_map_list, 
        name="map_list"),
    url(
        r'^map/(?P<pk>\d+)/delete/$',
        map_views.view_map_delete,
        name='map_delete'
    ),
    url(
        r'^map/delete/$',
        map_views.view_map_delete,
        name='map_delete_multiple'
    ),
    url(
        r'^map/$', 
        map_views.view_new_map, 
        name='map_view'
    ),
    url(
        r'permissions/update/(?P<map_id>\d+)/$',
        map_views.view_update_map_permissions,
        name='map_permissions'
    ),
    url(
        r'^map/create/$', 
        map_views.view_map_create, 
        name='map_create'
    ),
]

urlpatterns += [
    url(r'^map/(?P<map_id>[\d]+)/update/settings/$',
        ls_views.MapUpdate.as_view(), name='map_update'),
    url(r'^map/(?P<map_id>[\d]+)/update/permissions/$',
        ls_views.UpdateMapPermissions.as_view(),
        name='map_update_permissions'),
    url(r'^map/(?P<map_id>[\d]+)/update/delete/$',
        ls_views.MapDelete.as_view(), name='map_delete'),
    url(r'^map/(?P<map_id>[\d]+)/update/clone/$',
        ls_views.MapClone.as_view(), name='map_clone'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/create/$',
        ls_views.DataLayerCreate.as_view(), name='datalayer_create'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/update/(?P<pk>\d+)/$',
        ls_views.DataLayerUpdate.as_view(), name='datalayer_update'),
    url(r'^map/(?P<map_id>[\d]+)/datalayer/delete/(?P<pk>\d+)/$',
        ls_views.DataLayerDelete.as_view(), name='datalayer_delete'),
]

urlpatterns += [

    # Deployments
    url(
        r'^deployment/$',
        RedirectView.as_view(url=reverse_lazy('geomap:deployment_list')),
        name='deployment_index'
    ),
    url(
        r'^deployment/list/$',
        deployment_views.view_deployment_list,
        name='deployment_list'
    ),
    url(
        r'^deployment/detail/(?P<pk>\d+)/$',
        deployment_views.view_deployment_detail,
        name='deployment_detail'
    ),
    url(
        r'^deployment/delete/(?P<pk>\d+)/$',
        deployment_views.view_deployment_delete,
        name='deployment_delete'
    ),
    url(
        r'^deployment/delete/$',
        deployment_views.view_deployment_delete,
        name='deployment_delete_multiple'
    ),
    url(
        r'^deployment/create/$',
        deployment_views.view_deployment_create,
        name='deployment_create'
    ),
    url(
        r'^deployment/update/(?P<pk>\d+)/$',
        deployment_views.view_deployment_update,
        name='deployment_update'
    ),
    url(
        r'^deployment/bulk-update/$',
        deployment_views.view_deployment_bulk_update,
        name='deployment_bulk_update'
    ),
    url(
        r'^deployment/bulk-create/$',
        deployment_views.view_deployment_bulk_create,
        name='deployment_bulk_create'
    ),
    url(
        r'deployment/import/$',
        deployment_views.view_deployment_import,
        name='deployment_import'
    ),
]

trapper/trapper-project/trapper/apps/media_classification/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url, include
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from rest_framework.routers import DefaultRouter
from rest_framework.urlpatterns import format_suffix_patterns

from trapper.apps.media_classification.views import (
    api as classification_api_views
)
from trapper.apps.media_classification.views import (
    classifications as classifications_views,
    user_classifications as user_classifications_views,
    projects as projects_views,
    classificators as classificators_views,
    sequences as sequences_views 
)


router = DefaultRouter(trailing_slash=False)

router.register(
    r'classificators',
    classification_api_views.ClassificatorViewSet,
    base_name='api-classificator'
)

router.register(
    r'user-classifications',
    classification_api_views.UserClassificationViewSet,
    base_name='api-user-classification'
)

router.register(
    r'classifications',
    classification_api_views.ClassificationViewSet,
    base_name='api-classification'
)

router.register(
    r'classifications_map',
    classification_api_views.ClassificationMapViewSet,
    base_name='api-classification-map'
)

router.register(
    r'classification-projects',
    classification_api_views.ClassificationProjectViewSet,
    base_name='api-classification-project'
)

router.register(
    r'classification-project-collections',
    classification_api_views.ClassificationProjectCollectionViewSet,
    base_name='api-classification-project-collection'
)

router.register(
    r'sequences',
    classification_api_views.SequenceViewSet,
    base_name='api-sequence'
)

router.register(
    r'classification/(?P<collection_pk>\d+)/(?P<current_resource_pk>\d+)/resources/$',
    classification_api_views.ClassificationResourcesViewSet,
    base_name='api-classification-resources'
)

urlpatterns = [
    url(r'^api/', include(router.urls)),
    url(
        r'^api/classifications/results/(?P<project_pk>\d+)/',
        classification_api_views.ClassificationResultsView.as_view(),
        name='api-classification-results'
    ),
    url(
        r'^api/classifications/results/agg/(?P<project_pk>\d+)/',
        classification_api_views.ClassificationResultsAggView.as_view(),
        name='api-classification-results-agg'
    ),
    url(
        r'^api/classifications/import',
        classification_api_views.ClassificationImport.as_view(),
        name='api-classification-import'
    )
]

urlpatterns += [

    url(
        r'^$',
        RedirectView.as_view(
            url=reverse_lazy('media_classification:project_list')
        ),
        name='project_index'
    ),

    # Project views
    url(
        r'project/list/$',
        projects_views.view_project_list, 
        name='project_list'
    ),
    url(
        r'project/detail/(?P<pk>\d+)/$',
        projects_views.view_project_detail,
        name='project_detail'
    ),

    url(
        r'project/create/$', 
        projects_views.view_project_create,
        name='project_create'
    ),
    url(
        r'project/update/(?P<pk>\d+)/$', 
        projects_views.view_project_update,
        name='project_update'
    ),
    url(
        r'project/delete/(?P<pk>\d+)/$',
        projects_views.view_project_delete,
        name='project_delete'
    ),
    url(
        r'^project/delete/$',
        projects_views.view_project_delete,
        name='project_delete_multiple'
    ),
    url(
        r'project/collection/add/$',
        projects_views.view_project_collection_add,
        name='project_collection_add'
    ),
    url(
        r'project/collection/delete/(?P<pk>\d+)/$',
        projects_views.view_project_collection_delete,
        name='project_collection_delete'
    ),
    url(
        r'^project/collection/delete/$',
        projects_views.view_project_collection_delete,
        name='project_collection_delete_multiple'
    ),

    # Classificator views
    url(
        r'classificator/list/$', 
        classificators_views.view_classificator_list,
        name='classificator_list'
    ),
    url(
        r'classificator/detail/(?P<pk>\d+)/$',
        classificators_views.view_classificator_detail, 
        name='classificator_detail'
    ),

    url(
        r'classificator/create/$', 
        classificators_views.view_classificator_create,
        name='classificator_create'
    ),
    url(
        r'classificator/update/(?P<pk>\d+)/$',
        classificators_views.view_classificator_update,
        name='classificator_update'
    ),
    url(
        r'classificator/clone/(?P<pk>\d+)/$',
        classificators_views.view_classificator_clone,
        name='classificator_clone'
    ),
    url(
        r'^classificator/delete/(?P<pk>\d+)/$',
        classificators_views.view_classificator_delete,
        name='classificator_delete'
    ),
    url(
        r'^classificator/delete/$',
        classificators_views.view_classificator_delete,
        name='classificator_delete_multiple'
    ),

    # Sequence views
    url(
        r'sequence/create/$',
        sequences_views.view_sequence_change,
        name='sequence_create'
    ),
    url(
        r'sequence/update/$',
        sequences_views.view_sequence_change,
        name='sequence_update'
    ),
    url(
        r'sequence/change/$',
        sequences_views.view_sequence_change,
        name='sequence_change'
    ),
    url(
        r'sequence/delete/$',
        sequences_views.view_sequence_delete,
        name='sequence_delete'
    ),
    url(
        r'^sequence/build/$',
        sequences_views.view_sequence_build,
        name='sequence_build'
    ),

    # Classification views
    url(
        r'classification/detail/(?P<pk>\d+)/$',
        classifications_views.view_classification_detail,
        name='classification_detail'
    ),
    url(
        r'^classification/list/(?P<pk>\d+)/$',
        classifications_views.view_classification_list,
        name='classification_list'
    ),
    url(
        r'classification/import/$',
        classifications_views.view_classification_import,
        name='classification_import'
    ),
    url(
        r'classification/import/(?P<pk>\d+)/$',
        classifications_views.view_classification_import,
        name='classification_import'
    ),
    url(
        r'classification/export/(?P<pk>\d+)/$',
        classifications_views.view_classification_export,
        name='classification_export'
    ),
    url(
        r'classification/form/(?P<pk>\d+)/$',
        classifications_views.view_classification_tag,
        name='classification_tag'
    ),
    url(
        r'classification/delete/(?P<pk>\d+)/$',
        classifications_views.view_classification_delete,
        name='classification_delete'
    ),
    url(
        r'classification/delete/$',
        classifications_views.view_classification_delete,
        name='classification_delete_multiple'
    ),
    url(
        r'classify/(?P<project_pk>\d+)/(?P<collection_pk>\d+)/$',
        classifications_views.view_classify_collection,
        name='classify_collection'
    ),
    url(
        r'classify/(?P<pk>\d+)/$',
        classifications_views.view_classify_resource,
        name='classify'
    ),
    url(
        r'classify/(?P<pk>\d+)/user/(?P<user_pk>\d+)/$',
        classifications_views.view_classify_resource,
        name='classify_user'
    ),
    url(
        r'classify/approve/(?P<pk>\d+)/$',
        classifications_views.view_classify_approve,
        name='classify_approve'
    ),

    # UserClassification views
    url(
        r'user_classification/list/(?P<pk>\d+)/$',
        user_classifications_views.view_user_classification_list,
        name='user_classification_list'
    ),
    url(
        r'user_classification/approve/(?P<pk>\d+)/$',
        user_classifications_views.view_user_classification_bulk_approve,
        name='user_classification_bulk_approve'
    )

]

trapper/trapper-project/trapper/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.gis import admin as admin_gis
from django.conf import settings
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from trapper.apps.accounts.views import accounts as accounts_views

admin.autodiscover()

urlpatterns = [
    # Overrides
    # Overwrite account inactive url provided by django-allauth so user
    # is redirected to homepage instead of templateless inactive user
    url(
        r'^account/inactive/$',
        RedirectView.as_view(url=reverse_lazy('trapper_index')),
        name='account_inactive'
    ),
    # Trapper homepage
    url(
        r'^$',
        accounts_views.view_index,
        name='trapper_index'
    ),
    # Media classification urls
    url(
        r'^media_classification/',
        include(
            'trapper.apps.media_classification.urls',
            namespace='media_classification'
        )
    ),
    # Research urls
    url(
        r'^research/',
        include(
            'trapper.apps.research.urls',
            namespace='research'
        )
    ),
    # Storage urls
    url(
        r'^storage/',
        include(
            'trapper.apps.storage.urls',
            namespace='storage'
        )
    ),
    # Messaging urls
    url(
        r'^messaging/',
        include(
            'trapper.apps.messaging.urls',
            namespace='messaging'
        )
    ),
    # Accounts urls
    url(
        '',
        include('django.contrib.auth.urls')
    ),
    url(
        r'^accounts/',
        include(
            'trapper.apps.accounts.urls',
            namespace='accounts'
        )
    ),
    url(
        r'^account/',
        include('allauth.urls')
    ),
    # GeoMap urls
    url(
        r'^geomap/',
        include(
            'trapper.apps.geomap.urls',
            namespace='geomap'
        )
    ),
    # Comments
    url(
        r'^comments/',
        include(
            'trapper.apps.comments.urls',
            namespace='comments'
        )
    ),
    # Sendfile urls
    url(
        r'^serve/',
        include(
            'trapper.apps.sendfile.urls',
            namespace='sendfile'
        )
    ),
    # Forum
    url(
        r'^forum/',
        include(
            'djangobb_forum.urls',
            namespace='djangobb'
        )
    ),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^admin_gis/', include(admin_gis.site.urls)),
    url(r'', include('leaflet_storage.urls')),
    # REST API Swagger docs
    url(r'^docs/api/', include('rest_framework_swagger.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = urlpatterns + [
        url(
            r'^__debug__/', 
            include(debug_toolbar.urls)
        )
    ] + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    ) + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classification_export.html
{% extends "index.html" %}

{% load common_tags %}
{% load crispy_forms_tags %}

{% block data_app %}classification::upload{% endblock data_app %}

{% block main_menu %}{% nav_active 'menu_media_classification' %}{{ block.super }}{% endblock main_menu %}

{% block content %}
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Export classifications</h2>
      </div>

      <form action="" method="post" enctype="multipart/form-data" class="panel-body">
        {% crispy form form.helper %}
        <fieldset>
          <button type="submit" class="btn btn-primary">Submit</button>
        </fieldset>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/classification_import.html
{% extends "index.html" %}

{% load common_tags %}
{% load crispy_forms_tags %}

{% block data_app %}classification::upload{% endblock data_app %}

{% block main_menu %}{% nav_active 'menu_media_classification' %}{{ block.super }}{% endblock main_menu %}

{% block content %}
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title">Import classifications</h2>
      </div>

      <form action="" method="post" enctype="multipart/form-data" class="panel-body">
        {% crispy form form.helper %}
        <fieldset>
          <button type="submit" class="btn btn-primary">Submit</button>
        </fieldset>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/form_tag.html
{% load crispy_forms_tags %}
<form action="{% url 'media_classification:classification_tag' pk=project.pk %}" class="panel-body" method="post">
    <fieldset>

        {% for field in form %}
            <div class="checkbox">
                {% if not field.is_hidden %}
                    <label>
                {% endif %}

                {{ field }}

                {% if not field.is_hidden %}
                    {{ field.label }}
                    </label>
                {% endif %}
            </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Add tags</button>
    </fieldset>
</form>

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/grid.html
{% extends "common/grid.html" %}

{% block breadcrumbs %}
<div class="row">
  <div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2 class="panel-title">
        <span class="fa fa-flask"></span> <a href="{% url 'research:project_detail' pk=grid_context.project.research_project.pk %}">{{ grid_context.project.research_project.acronym }}</a> >
        <span class="fa fa-cubes"></span> <a href="{% url 'media_classification:project_detail' pk=grid_context.project.pk %}">{{ grid_context.project.name }}</a> > <strong>Results</strong>
      </h2>
    </div>
  </div>
</div>
</div>
{% endblock %}

{% block filters %}

{% for definition in grid_context.filters %}
<div class="form-group form-filter">
  <label for="{{ definition.name }}" class="control-label">{{ definition.label }}</label>
  
  <{{ definition.tag.name }}
      id="{{ definition.name }}"
      class="form-control"
      filter-text="{{ definition.name }}"
      filter-service="filter"
      ng-model="filters['{{ definition.name }}']"
      {% if definition.values %}
      ng-options="option.value as option.label for option in [{% for key, val in definition.values %}{'label': '{{ key }}', 'value': '{{ val }}'}{% if not forloop.lat %},{% endif %}{% endfor %}]"
      {% endif %}
      {% if definition.tag.is_block %}>
  </{{ definition.tag.name }}>
  {% else %}/>
  {% endif %}
</div>
{% endfor %}

<div class="form-group form-filter">
  <label for="status" class="control-label">Approved</label>
  <select
     id="status"
     class="form-control"
     filter-text="status"
     filter-service="filter"
     ng-model="filters.status"
     ng-options="option.value as option.label for option in optionList.bool">
  </select>
</div>

<div class="form-group form-filter form-datepicker">
  <label class="control-label">Rec. date</label>
  <div class="input-group input-daterange"
       filter-daterange="filters.rdate"
       filter-name="'resource.rdate'"
       filter-service="filter">
    <input
       type="text"
       class="form-control"
       placeholder="from"
       >
    <span class="input-group-addon">
      <span class="fa fa-calendar"></span>
    </span>
    <input
       type="text"
       class="form-control"
       placeholder="to"
       >
  </div>
</div>

<div class="form-group form-filter form-datepicker">
  <label class="control-label">Rec. time</label>
  <div class="input-group input-daterange"
       filter-timerange="filters.rtime"
       filter-name="'resource.rtime'"
       filter-service="filter">
    <input
       type="text"
       class="form-control"
       placeholder="from"
       >
    <span class="input-group-addon">
      <span class="fa fa-clock-o"></span>
    </span>
    <input
       type="text"
       class="form-control"
       placeholder="to"
       >
  </div>
</div>

<div class="form-group form-filter">
  <label for="type" class="control-label">File type</label>
  <select
     id="type"
     class="form-control"
     filter-text="ftype"
     filter-service="filter"
     ng-model="filters.ftype"
     ng-options="option.value as option.label for option in optionList.media">
  </select>
</div>

<div class="form-group form-filter-full">
  <label for="collections" class="control-label">Collections</label>
  <select
     type="text"
     id="collection"
     class="select2-default"
     multiple
     ng-model="filters.collection"
     filter-tokens="collection.name"
     filter-service="filter">
    {% for collection in grid_context.collections %}
    <option value="{{ collection.0 }}">{{ collection.1 }}</option>
    {% endfor %}
  </select>
</div>

<div class="form-group form-filter-full">
  <label for="deployments" class="control-label">Deployments</label>
  <select
     type="text"
     id="deployments"
     class="select2-default"
     multiple
     ng-model="filters.deployment"
     filter-tokens="resource.deployment_id"
     filter-service="filter">
    {% for deployment in grid_context.deployments %}
    <option value="{{ deployment.0 }}">{{ deployment.1 }}</option>
    {% endfor %}
  </select>
</div>

{% endblock %}

{% block my_objects %}
{% if user.is_authenticated %}
<button
   type="button"
   class="btn btn-default"
   ng-class="{ active: filters.owner }"
   ng-model="filters.owner"
   ng-init="filters.owner = false"
   ng-click="filterOwner()"
   filter-checkbox="{ name: 'owner', value: '{{ user.pk }}' }"
   filter-service="filter">My resources</button>
{% endif %}
{% endblock %}

{% block custom_actions %}

{% if grid_context.is_admin %}
<action-create-collection ng-disabled="!data.selectedCounter" ng-click="execute('{% url "storage:collection_create" %}','media_classification')">
</action-create-collection>
{% endif %}
{% url 'geomap:map_view' as new_map_url %}
<action-show-map data-type="classifications" data-url="{{ new_map_url }}" data-field="pk">
  <select>
    <option value="{{ new_map_url }}" selected>New map</option>
    {% for map in grid_context.maps %}
    <option value="{% url 'geomap:map' slug=map.slug pk=map.pk %}">{{ map }}</option>
    {% endfor %}
  </select>
</action-show-map>
<action-export-with-filters ng-click="execute('{% url "media_classification:api-classification-results" project_pk=grid_context.project.pk %}')">
</action-export-with-filters>

<!-- <button -->
<!--    type="button" -->
<!--    class="btn btn-default" -->
<!--    ng-class="{ active: showTags }" -->
<!--    ng-model="showTags" -->
<!--    ng-init="showTags = true" -->
<!--    ng-click="showTags = !showTags">Tags</button> -->

{% endblock%}

{% block custom_actions_list %}

{% if grid_context.is_admin %}
<li>
  <action-addto-collection ng-click="execute($event, '{% url "storage:collection_append" %}', '{% url "storage:api-collection-append-list" %}', 'media_classification')">
</action-addto-collection>
</li>
<li ng-class="{'disabled': !filters.owner}">
  <action-create-tags ng-click="execute($event, '{% url "media_classification:classification_tag" pk=grid_context.project.pk %}')">
</action-create-tags>
</li>
<li>
  <action-remove-selected ng-click="execute($event, '{% url "media_classification:classification_delete_multiple" %}')">
  </action-remove-selected>
</li>
{% endif %}

{% endblock%}

{% block table_cells %}

<td data-title="'Thumbnail'"><action-media ng-click="execute($event, record)"><img ng-src="{[{ record.resource.thumbnail_url }]}"></action-media></td>
<td data-title="'Type'" sortable="'resource.resource_type'" ng-bind-html="record.resource.resource_type | typesIcon"></td>
<td data-title="'Name'" sortable="'resource.name'">{[{ record.resource.name }]}</td>
<td data-title="'Date recorded'" sortable="'date_recorded'">{[{ record.resource.date_recorded | dateTZ: dateFormat.table }]}</td>
<td data-title="'Approved'" sortable="'status'" ng-bind-html="record.status | classifiedIcons"></td>
<td data-title="'Attributes'">
  <!-- ng-show="showTags" -->
  <h6>Static attributes:</h6>
  <div class="tags-list">
    <span 
       ng-repeat="(label, tag) in record.static_attrs" 
       ng-if="label != 'comments' && label != 'annotations'"
       class="label label-success">{[{ label }]}: {[{ tag }]}
    </span>
  </div>
  <!-- ng-show="showTags" -->
  <h6>Dynamic attributes:</h6>
  <div class="tags-list" ng-repeat="dynamic_attr in record.dynamic_attrs" ng-init="tagIndex = $index">
    <span
       ng-repeat="(label, tag) in dynamic_attr"
       ng-if="label != 'comments' && label != 'annotations'"
       class="label" title="{[{ tag }]}"
       ng-class="{'label-default': tagIndex % 2 == 0, 'label-success': tagIndex % 2 != 0}">{[{ label }]}: {[{ tag }]}</span>
  </div>
</td>

{% endblock %}

{% block table_cells_extra_actions %}
<td>
  <action-classify 
     ng-click="execute($event, record, 
               {{grid_context.project.deployment_based_nav|yesno:'true,false'}})">
  </action-classify>
</td>
{% endblock %}

trapper/trapper-project/trapper/apps/media_classification/templates/media_classification/classifications/list.html
{% extends "media_classification/index.html" %}

{% load common_tags %}

{% block ng_app %}ng-app="trapperGrid"{% endblock ng_app %}

{% block section_content %}
    {% with grid_context=classification_context %}
    {% include 'media_classification/classifications/grid.html' %}
    {% endwith %}
{% endblock section_content %}